auth_enabled: false  # Отключаем аутентификацию для простоты

server:
  http_listen_port: 3100  # Порт, на котором Loki принимает запросы от Grafana и Promtail

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # Хранение метаданных в памяти, может быть настроено на работу с внешними хранилищами, например, Consul или Etcd
      replication_factor: 1  # Количество реплик для метаданных, 1 реплика для минимальной настройки

schema_config:
  configs:
    - from: 2024-10-10
      store: boltdb  # Хранение индексов метаданных в boltdb
      object_store: filesystem  # Файловая система для хранения самих логов (chunks)
      schema: v11  # Схема хранения данных
      index:
        prefix: index_  # Префикс для индекса
        period: 168h  # Период хранения индексов (например, одна неделя)

storage_config:
  boltdb:
    directory: /loki/index  # Путь для хранения индексов
  filesystem:
    directory: /loki/chunks  # Путь для хранения самих логов (chunks)

limits_config:
  reject_old_samples: true  # Отвергаем слишком старые логи
  reject_old_samples_max_age: 168h  # Максимальный возраст логов, которые принимаются (168 часов = 7 дней)
